# Generated by Django 3.1.2 on 2020-10-13 21:12

import biodata.api.base
import biodata.api.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Study',
            fields=[
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False, null=True, verbose_name='created')),
                ('modified', models.DateTimeField(default=django.utils.timezone.now, editable=False, null=True, verbose_name='modified')),
                ('kf_id', biodata.api.base.KFIDField(default=biodata.api.models.study_id, editable=False, max_length=11, primary_key=True, serialize=False, unique=True)),
                ('short_name', models.CharField(max_length=25)),
                ('name', models.CharField(blank=True, default='Not Reported', max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
