# Generated by Django 3.1.2 on 2020-10-25 22:56

import biodata.api.base
import biodata.api.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Study',
            fields=[
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False, null=True, verbose_name='created')),
                ('modified', models.DateTimeField(default=django.utils.timezone.now, editable=False, null=True, verbose_name='modified')),
                ('kf_id', biodata.api.base.KFIDField(default=biodata.api.models.study_id, editable=False, max_length=11, primary_key=True, serialize=False, unique=True)),
                ('short_name', models.CharField(max_length=25)),
                ('name', models.CharField(blank=True, default='Not Reported', max_length=100, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False, null=True, verbose_name='created')),
                ('modified', models.DateTimeField(default=django.utils.timezone.now, editable=False, null=True, verbose_name='modified')),
                ('kf_id', biodata.api.base.KFIDField(default=biodata.api.models.participant_id, editable=False, max_length=11, primary_key=True, serialize=False, unique=True)),
                ('gender', models.CharField(choices=[('Female', 'Female'), ('Other', 'Other'), ('Male', 'Male')], default='Not Reported', max_length=50)),
                ('race', models.CharField(choices=[('More Than One Race', 'More Than One Race'), ('Black or African American', 'Black or African American'), ('Native Hawaiian or Other Pacific Islander', 'Native Hawaiian or Other Pacific Islander'), ('Other', 'Other'), ('White', 'White'), ('Asian', 'Asian'), ('American Indian or Alaska Native', 'American Indian or Alaska Native')], default='Not Reported', max_length=50, null=True)),
                ('ethnicity', models.CharField(choices=[('Hispanic or Latino', 'Hispanic or Latino'), ('Not Hispanic or Latino', 'Not Hispanic or Latino')], default='Not Reported', max_length=50, null=True)),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='api.study')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Biospecimen',
            fields=[
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False, null=True, verbose_name='created')),
                ('modified', models.DateTimeField(default=django.utils.timezone.now, editable=False, null=True, verbose_name='modified')),
                ('kf_id', biodata.api.base.KFIDField(default=biodata.api.models.biospecimen_id, editable=False, max_length=11, primary_key=True, serialize=False, unique=True)),
                ('analyte_type', models.CharField(choices=[('DNA', 'DNA'), ('Other', 'Other'), ('RNA', 'RNA')], default='Not Reported', max_length=50)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='biospecimens', to='api.participant')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
